### ISSUE TITLE
[RFC] Deprecate extractors & introducing mappings

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/SeoBundle#133]
## Current Issues

We are having 4 issues with the current Extractors mechanism:
1. The order in which they should be executed (https://github.com/symfony-cmf/SeoBundle/issues/107)
2. SeoMetadata should inherit (https://github.com/symfony-cmf/SeoBundle/issues/87)
3. There should be a way to turn on/off extractors per document (https://github.com/symfony-cmf/SeoBundle/issues/125)
4. Some caching is needed for the extractors (https://github.com/symfony-cmf/SeoBundle/issues/118#issuecomment-39678508)

(1) and (3) are especially pretty hard to solve using the extractors.

I think we should go in a complete new direction for 1.1, however that can make things more complicated. I don't know if that's really welcome, since this bundle is pretty nice because it's not complicated.
## Using Mappings

My idea was to use mappings instead of extractors. Instead of implementing some interfaces and introducing some wrapper methods which just call other functions, we should have a way to "map" some values of the document to SeoMetadata.

This can be done using the JmsSerializer. Some examples:

``` php
use Symfony\Cmf\Bundle\SeoBundle\Annotation as Seo;

class Page
{
    /**
     * @Seo\Title
     */
    protected $name;

    /**
     * @Seo\MetaKeywords({
     *     "strategy": "append"
     * })
     */
    protected $tags = array();

    /**
     * @Seo\MetaDescription(
     *     "stategy": "override"
     * })
     */
    protected $description;
}
```

Of course, we should also support Yaml and Xml mappings and mappings for methods. For instance:

``` yaml
Acme\BlogBundle\Document\Article:
    properties:
        title:
            title: ~
        tags:
            meta_keywords: { strategy: append }
        description:
            meta_description: { strategy: override }
```

``` xml
<seo-mapping class="Acme\BlogBundle\Document\Article">
    <property name="title">
        <seo type="title" />
    </property>

    <property name="tags">
        <seo type="meta_keywords">
            <option name="strategy">append</option>
        </seo>
    </property>

    <property name="description">
        <seo type="meta_description">
            <option name="strategy">override</option>
        </seo>
    </property>
</seo-mapping>
```
## Support Custom Data

Then we can also fix #131 by using a generic "Meta" mapping for custom meta values:

``` php
// ...
class Page
{
    /**
     * @Seo\Title
     * @Seo\Meta("og:title")
     */
    protected $name;
}
```

``` yaml
Acme\BlogBundle\Document\Article:
    properties:
        name:
            title: ~
            meta: { name: og:title }
```
## Keeping BC

Of course, we should be BC. So we should keep supporting the extractors, but deprecate it.
replaces https://github.com/symfony-cmf/SeoBundle/issues/118
