### ISSUE TITLE
Problem with SeoMetadata as Child, when looping over real children

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/SeoBundle#162]
I have no clue if that is a bug or just a use case, where the application needs to be changed. I added some SeoMetadata to the main news site of the cmf-website. With the new child mapping, this causes that node structure:

```
ROOT:
  cms:
    menu:
    content:
      talks:
      forum-php-paris-2013:
      symfonycon-2013-warszaw:
      php-benelux-2014:
      drupalcamp-2013-vienna:
      010php-2013-11-14-rotterdam:
    simple:
      news:
        seoMetadata:
        cmf-featured-on-symfony-com:
        cmf-sandbox-now-running-with-multiple-different-phpcr-implementations:
        jackalope-doctrine-dbal-now-compatible-with-postgresql-and-sqlite:
        symfony-cmf_at-the-create-js-hackathon-in-berlin:
        cmf-docs-and-standard-edition:
        cmf-website-update:
        demo-website-update:
        cmf-docs-moved:
        towards-version-1.0:
        how-to-survive-stabilization-phase:
        doctrine-dbal-repository-data-fixes:
        getting-closer-to-1-0-release:
        doctrine-dbal-repository-data-fixes-round2:
        symfony2-cmf-rc1-released:
        symfony2-cmf-1-0-0-released:
        conference-presence:
        cmf-best-symfony-opensource-project-2013:
        finally-1-1-0-RC1:
        cmf-workshop-phpday-it:
      get-started:
      get-involved:
      references:
      about:
    docs:
    wiki:
    demo:

```

The problem isn't that mapping, the problem is that the template, which shows the news entries in a list just loops over the children of `/cms/news` and tries to display path and content. That fails. Is that a fault of the SeoMetadata mapping? Can we avoid that? Or should the application be changed?
