### ISSUE TITLE
lastmod tag is empty

### ISSUE THREAD

**Issue by WillBBP** [symfony-cmf/SeoBundle#233]
We've used Symfony CMF SeoBundle to generate an XML sitemap and posted on StackOverflow re how to set the lastmod attribute in the sitemap... 

http://stackoverflow.com/questions/31339033/how-to-set-lastmod-symfony-cmf-seobundle-xml-sitemap

We're currently getting...

```
<url>
    <loc>https://somesite.com/somepage</loc>
    <lastmod/>
    <changefreq>always</changefreq>
</url>
```

Apparently... "this should never happen. either lastmod is undefined and there would be no tag, or it should be a valid lastmod value."

I'm not sure what config you would need to see to look into this, but in app/config.yml we have...

```
cmf_seo:
    persistence:
        phpcr:
            enabled: true
            manager_name: ~
    sonata_admin_extension: true
    sitemap: true
```
