### ISSUE TITLE
option to disable default loader / voter / guesser

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/SeoBundle#242]
the default things should be possible to disable. not sure how to not make this horribly verbose... ideas? just a global on/off?

**Comment by ElectricMaxxx** [comment]
Doesn't WE have a priority to overwrite them? This would he the first solution. 
The second would be to create a enable/disable map which can be passed to the voters. They can decline when their own option is set to false. Same for guesser, they can decline in `supports()` method.

**Comment by dbu** [comment]
for guessers yes, only if i want some value not at all, there is still a problem. for the loader, its more important because i might have phpcr enabled but need my own, more clever, loader instead of the default one...

maybe a section in the defaults? 
```yaml
cmf_seo:
    sitemap:
        defaults:
            loaders: none|all|phpcr
            guessers: none|all|<comma separated list>
            voters: none|all|publish-workflow            
```

then in the DI extension we just remove the services from the container that are not activated.
