### ISSUE TITLE
xml-config for default title / xsd-file

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/SeoBundle#48]
That issue should solve problem with the configuration (xml, xsd) for the default title configuration.

The default title can contain a simple string or a list of key-value pairs for the multilang support. Both examples should be possible:

```
cmf_seo:
    title:
        default: Default title
```

```
cmf_seo:
    title:
        default: 
            en: Default title
            de: Default Title
```
