### ISSUE TITLE
use translation keys for title and description

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/SeoBundle#59]
If we would use translation keys (and an optional translation domain) for title and description, the configuration would become simpler and this bit of translation could become more global. we could offload some work to the translation component.

we would define what placeholder to use for the [message placeholder](http://symfony.com/doc/current/components/translation/usage.html#component-translation-placeholders)

```
# messages.en.yml
my_title: "CMF - %title% - Symfony2 Content Management Framework"

# config.yml
cmf_seo:
    title_key: my_title
    title_domain: messages
```

all the logic about the current locale and whatever would be left to the translation framework i would say. if somebody is doing weird things with the locale, he just needs to make sure to also update whatever translation uses to know the current locale.
